FROM node:20

WORKDIR /app

COPY apps/core/package*.json ./apps/core/
COPY apps/auth-service/package*.json ./apps/auth-service/

WORKDIR /app/apps/core
RUN npm install

WORKDIR /app/apps/auth-service
RUN npm install

COPY apps/auth-service/prisma ./prisma
RUN npx prisma generate

WORKDIR /app
COPY apps/core ./apps/core
COPY apps/auth-service ./apps/auth-service

WORKDIR /app/apps/auth-service

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
