FROM node:20

WORKDIR /apps

COPY core/package*.json core/
COPY core/tsconfig.json core/

COPY auth-service/package*.json auth-service/
COPY auth-service/tsconfig.json auth-service/

WORKDIR /apps/core
RUN npm install

WORKDIR /apps/auth-service
RUN npm install

COPY auth-service/prisma ./prisma
RUN npx prisma generate

WORKDIR /apps
COPY core/src core/src
COPY auth-service/src auth-service/src

WORKDIR /apps/core
RUN npm run build

WORKDIR /apps/auth-service

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
